export const JobStatus = {
  QUEUED: "QUEUED",
  RUNNING: "RUNNING",

  ACCEPTED: "ACCEPTED",
  COMPILE_ERROR: "COMPILE_ERROR",
  RUNTIME_ERROR: "RUNTIME_ERROR",
  TIME_LIMIT_EXCEEDED: "TIME_LIMIT_EXCEEDED",
  MEMORY_LIMIT_EXCEEDED: "MEMORY_LIMIT_EXCEEDED",

  SYSTEM_ERROR: "SYSTEM_ERROR"
};

