global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'code-executor-monitor'

scrape_configs:
  - job_name: 'code-executor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:4000']
    scrape_interval: 5s
    scrape_timeout: 5s
